# Generated by Django 3.2.5 on 2021-09-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymentorder_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('session_id', models.CharField(max_length=200, null=True, verbose_name='Session ID')),
                ('payment_success', models.BooleanField(default=False, null=True, verbose_name='Payment Success')),
                ('payment_service', models.CharField(max_length=200, null=True, verbose_name='Payment Service Name')),
                ('additional_info', models.TextField(null=True, verbose_name='Entire Session Data')),
                ('date', models.DateField(null=True, verbose_name='Transaction Date')),
            ],
        ),
    ]
