# Generated by Django 3.2.5 on 2021-09-21 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0009_subscription_subid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Name'),
        ),
    ]
